### PR TITLE
fix Language parameter always set to LanguageIndonesian

### PR DESCRIPTION
**Pull request by yahyai-0**

### CODE REVIEW

**Comment by febriliankr** [comment]
LanguageIndonesian is a reference to a variable:

```
var LanguageIndonesian = TemplateLanguage{
		Code: "id",
	}
```

We can further add more languages by adding LanguageEnglishUS, LanguagePortugese, etc

It is not helpful to rename LanguageIndonesian to `language` as it makes the variable unimported and non-descriptive

**Comment by yahyai-0** [comment]
I mean that the parameter "lanaguage" of the function  "createSendWithTemplateRequest" is never used, because the template language variable always initiated with "LanguageIndonesian".

it is now like this
```
func (wa *Whatsapp) createSendWithTemplateRequest(receiverPhoneNumber string, templateName string, **language** TemplateLanguage, components []Components) (res SendWithTemplateRequest) {
	return SendWithTemplateRequest{
		MessagingProduct: "whatsapp",
		To:               receiverPhoneNumber,
		Type:             "template",
		Template: Template{
			Name:     templateName,
			Language: **LanguageIndonesian**,
			// Components can be empty if you don't want to send any parameters
			Components: components,
		},
	}
}
```
after edit.
```
func (wa *Whatsapp) createSendWithTemplateRequest(receiverPhoneNumber string, templateName string, language TemplateLanguage, components []Components) (res SendWithTemplateRequest) {
	return SendWithTemplateRequest{
		MessagingProduct: "whatsapp",
		To:               receiverPhoneNumber,
		Type:             "template",
		Template: Template{
			Name:     templateName,
			Language: **language**,
			// Components can be empty if you don't want to send any parameters
			Components: components,
		},
	}
}
```

**Comment by febriliankr** [comment]
The issue you mentioned has been solved with the latest v1.0.8 release where I added all of the supported languages as constants, and changed the default language in the whatsapp.NewWhatsapp(...) initiation to English.

**Comment by masewo** [comment]
@febriliankr But the problem is that the language, that is passed here: https://github.com/febriliankr/whatsapp-cloud-api/blob/6769672637d74e44ad9fa6221c5eb9d5b8e14974/whatsapp.go#L94 is not used here: https://github.com/febriliankr/whatsapp-cloud-api/blob/6769672637d74e44ad9fa6221c5eb9d5b8e14974/whatsapp.go#L101

**Pull request closed without merging**
